version: '3.4'

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "database#2022"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - C:\dados\volumes\sqlserver:/var/opt/mssql/data

  finalprojectcsharptrybe:
    image: ${DOCKER_REGISTRY-}finalprojectcsharptrybe
    build:
      context: .
      dockerfile: FinalProjectCSharpTrybe/Dockerfile
    environment:
      DbServer: "mssql-server"
      DbPort: "1433"
      DbUser: "SA"
      DbPassword: "database#2022"
      Database: "Tryitter"
    ports: 
      - "8090:80"
      - "443:443"